/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SuitsRouteImport } from './routes/suits'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminCrmIndexRouteImport } from './routes/admin.crm.index'
import { Route as AdminCrmLeadsIndexRouteImport } from './routes/admin.crm.leads.index'
import { Route as AdminCrmLeadsIdRouteImport } from './routes/admin.crm.leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitsRoute = SuitsRouteImport.update({
  id: '/suits',
  path: '/suits',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmIndexRoute = AdminCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmLeadsIndexRoute = AdminCrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmLeadsIdRoute = AdminCrmLeadsIdRouteImport.update({
  id: '/crm/leads/$id',
  path: '/crm/leads/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/heritage': typeof HeritageRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/suits': typeof SuitsRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/crm/leads/': typeof AdminCrmLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/heritage': typeof HeritageRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/suits': typeof SuitsRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/admin/crm': typeof AdminCrmIndexRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/crm/leads': typeof AdminCrmLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/heritage': typeof HeritageRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/suits': typeof SuitsRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/crm/': typeof AdminCrmIndexRoute
  '/admin/crm/leads/$id': typeof AdminCrmLeadsIdRoute
  '/admin/crm/leads/': typeof AdminCrmLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/heritage'
    | '/search'
    | '/shop'
    | '/suits'
    | '/wishlist'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/collections/'
    | '/journal/'
    | '/admin/crm/'
    | '/admin/crm/leads/$id'
    | '/admin/crm/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/heritage'
    | '/search'
    | '/shop'
    | '/suits'
    | '/wishlist'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/admin'
    | '/collections'
    | '/journal'
    | '/admin/crm'
    | '/admin/crm/leads/$id'
    | '/admin/crm/leads'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bag'
    | '/checkout'
    | '/contact'
    | '/craft'
    | '/heritage'
    | '/search'
    | '/shop'
    | '/suits'
    | '/wishlist'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/collections/'
    | '/journal/'
    | '/admin/crm/'
    | '/admin/crm/leads/$id'
    | '/admin/crm/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CraftRoute: typeof CraftRoute
  HeritageRoute: typeof HeritageRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SuitsRoute: typeof SuitsRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suits': {
      id: '/suits'
      path: '/suits'
      fullPath: '/suits'
      preLoaderRoute: typeof SuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm/': {
      id: '/admin/crm/'
      path: '/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminCrmIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/leads/': {
      id: '/admin/crm/leads/'
      path: '/crm/leads'
      fullPath: '/admin/crm/leads/'
      preLoaderRoute: typeof AdminCrmLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/leads/$id': {
      id: '/admin/crm/leads/$id'
      path: '/crm/leads/$id'
      fullPath: '/admin/crm/leads/$id'
      preLoaderRoute: typeof AdminCrmLeadsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCrmIndexRoute: typeof AdminCrmIndexRoute
  AdminCrmLeadsIdRoute: typeof AdminCrmLeadsIdRoute
  AdminCrmLeadsIndexRoute: typeof AdminCrmLeadsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCrmIndexRoute: AdminCrmIndexRoute,
  AdminCrmLeadsIdRoute: AdminCrmLeadsIdRoute,
  AdminCrmLeadsIndexRoute: AdminCrmLeadsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CraftRoute: CraftRoute,
  HeritageRoute: HeritageRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SuitsRoute: SuitsRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
